---
- hosts: localhost
  tasks:
  - name: create a file
    file: state=touch path=/home/saitama/ansible-test
  - name: edit file
    lineinfile: line="algo de texto" path=/home/saitama/ansible-test
    register: lif_info
